### ISSUE TITLE
Generating code method issue(mac & 1.4.0)

### ISSUE THREAD

**Issue by chensivan** [sikuli/sikuli-slides#11]
I'm not sure how much of work that this method is supposed to finish, but here is what I had issues with. In the Java code that I generated by running the command line:

$ java -jar sikuli-slides-1.4.0.jar generate login.pptx 

there are three slides.They are opening Twitter, typing name, and typing account. Here are some issues that I came across in the code. 
First, the global public static float variable is name "DEFAULT_MINSCORE" at the beginning, but it generates "DEFAULT_MIN_SCORE" as the parameter value for the target.setMinScore method within the step function. 

Second, both "screenRegin" variable and "mouse" variable in the step function are undefined. 

Third, in the "findImageByName()" function, the "File.pathSeparator" doesn't work on my mac, and when I change it to "File.separator", it works fine; in another word, it loads the images.

Fourth, my first slide is open an URL, but the step1 function in the generated code has only one line which is "return true".

**Comment by doubleshow** [comment]
code generation is no longer considered an important feature we want to further develop.
