### ISSUE TITLE
Recorded file is not a valid pptx

### ISSUE THREAD

**Issue by JonasPf** [sikuli/sikuli-slides#18]
When I was trying to run a generated file I got this error:
File is not a valid pptx: c:\data\2013-09-19-12-32-54.pptx
Execution failed because java.io.IOException

I had to open the file in Powerpoint and save it under a different name to get rid of this error.

Could be related to #8 because I had to apply the workaround I mentioned there to get the recording working.

**Comment by chensivan** [comment]
I think this is also related to #15 , I reported a similar issue which has to do with the names of the file.

**Comment by doubleshow** [comment]
fixed.
