### ISSUE TITLE
.jar download missing

### ISSUE THREAD

**Issue by andOlga** [sikuli/sikuli-slides#23]
Hello. Currently, the download links on slides.sikuli.org pointing to the jars are broken. Please fix them.

**Comment by bj0** [comment]
Is there another source to get the jar files?

**Comment by frinsen** [comment]
+1

**Comment by malamunisamy** [comment]
+1

**Comment by nbui** [comment]
+1

**Comment by doubleshow** [comment]
will fix this in the upcoming 1.5 release. stay tuned
