### ISSUE TITLE
pass keyboard (tab enter)

### ISSUE THREAD

**Issue by arnos** [sikuli/sikuli-slides#25]
Sikuli supports this but Sikuli slides doesn't seem to recognize anyway of hitting the tab or return key or the function keys.

Is it possible to have a key action (eg create a box with "Key Enter") or recognize the special characters (eg \n or \t) in https://github.com/sikuli/sikuli/blob/develop/sikuli-script/src/main/java/org/sikuli/script/Key.java for "the" Type action

**Comment by arnos** [comment]
Can be closed as corrected in pull request #26

**Comment by doubleshow** [comment]
Thank you for correcting this issue!
