### ISSUE TITLE
Recorder doesn't work at all on mac(mac & 1.4.0)

### ISSUE THREAD

**Issue by chensivan** [sikuli/sikuli-slides#8]
For the "Recorder" method, when i ran the command line: 

$ java -jar sikuli-slides-1.4.0.jar record

It does show the two prompts. 
Press [Ctrl-Shift-2] to start recording
Press [Ctrl-Shift-ESC] to stop recording

However, at the same time, i cannot do any other actions on any other apps, except pressing either of the buttons in the prompts. After i press start recording, i still cannot do any other action on any other apps, no recording happens. And when I stopped the recording, it shows the following error in the terminal:

Recording is stopped.
Exception in thread "main" java.lang.NullPointerException
at org.sikuli.recorder.Utils.stream2file(Utils.java:16)
at org.sikuli.recorder.pptx.PPTXGenerator.createSkeletonDir(PPTXGenerator.java:164)
at org.sikuli.recorder.pptx.PPTXGenerator.generate(PPTXGenerator.java:153)
at org.sikuli.slides.apps.RecorderMain.main(RecorderMain.java:55)
at org.sikuli.slides.apps.Main.main(Main.java:34)

**Comment by sssuneet** [comment]
Please provide some input as I am facing the same issue while recording..Thanks

**Comment by inotives** [comment]
Hi i am running sikuli-slides-1.4.0 on windows. the recorder after i press Ctrl+Shift_Esc, the same issue as mention above arise. 
Hope to see a fix soon. thanks.

**Comment by JonasPf** [comment]
Same issue here (Java 1.7, Windows 7)

I looked at the code on github and it seems like it's missing the file skeleton.pptx. I was able to work around this problem by copying all files from the src\main\resources\org\sikuli\recorder\pptx into the jar file. After that recording worked fine (although it didn't record double clicks and typing but I assume this is just not supported yet).

**Comment by XinyuWangAVG** [comment]
Having the same issue with 1.4.0 on mac os x.

**Comment by doubleshow** [comment]
This is related to issue #13 and has been fixed.
